"""add tenant user relationship

Revision ID: 484525a986e7
Revises: cad6eb4ceda9
Create Date: 2026-08-27 09:53:06.497324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '484525a986e7'
down_revision = 'cad6eb4ceda9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint('uq_tenants_user_id', ['user_id'])
        batch_op.create_foreign_key('fk_tenants_user_id_users', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tenants_user_id_users', type_='foreignkey')
        batch_op.drop_constraint('uq_tenants_user_id', type_='unique')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###