"""Add tenant move in date

Revision ID: 59754fbde2b4
Revises: 5d89a3a65641
Create Date: 2026-08-25 22:04:05.138880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59754fbde2b4'
down_revision = '5d89a3a65641'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('move_in_date', sa.Date(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_column('move_in_date')

    # ### end Alembic commands ###
