"""Add total units to properties

Revision ID: 5d89a3a65641
Revises: a301fa35b8cb
Create Date: 2026-08-18 15:53:34.571607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d89a3a65641'
down_revision = 'a301fa35b8cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_units', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_column('total_units')

    # ### end Alembic commands ###
